[project]
name = "terraform-aws-ecs-events-to-slack"
version = "0.1.0"
description = "Lambda function to send ECS events to Slack"
authors = [
    { name = "Fivexl" }
]

requires-python = ">=3.10"
dependencies = [
    "boto3==1.26.90",
    "botocore==1.29.90",
    "jmespath==1.0.1",
    "python-dateutil==2.8.2",
    "s3transfer==0.6.1",
    "six==1.16.0",
    "urllib3==1.26.19",
]

[tool.uv]
managed = true
package = false

[tool.uv.sources]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# We can keep your dev tools here as well
[dependency-groups]
dev = [
    "pytest>=7.2.2",
    "black>=23.1.0",
    "ruff>=0.0.267",
]